version: "3"

services:
  db:
    build:
      context: .
      dockerfile: ./Docker/Postgresql/Dockerfile
      args:
        - DB_LANG=ja_JP
    container_name: "db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./Postgresql//Database:/var/lib/postgresql
      - ./Postgresql/init:/docker-entrypoint-initdb.d
  backend:
    build:
      context: .
      dockerfile: ./Docker/React/Dockerfile
      args:
        - DB_LANG=ja_JP
    container_name: "backend"
    command: ash -c "npm install && npm run start"
    ports:
      - "3001:3001"
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    volumes:
      - ./backend:/app
      - node_modules_volume1:/app/node_modules
  app:
    build:
      context: .
      dockerfile: ./Docker/React/Dockerfile
      args:
        - DB_LANG=ja_JP
    container_name: "app"
    command: ash -c "npm install && npm run start"
    ports:
      - "3002:3002"
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    volumes:
      - ./my_kakeibo:/app
      - node_modules_volume2:/app/node_modules
    depends_on:
      - db
      - backend
volumes:
  node_modules_volume1:
  node_modules_volume2: