\c incomeandexpenditure

INSERT INTO Users(USER_NAME, PASSWORD) VALUES ('User1', 'password1');
INSERT INTO Users(USER_NAME, PASSWORD) VALUES ('User2', 'password2');


INSERT INTO IncomeAndExpenditure(USER_ID, DATE, IN_OUT, MONEY_SOURCE_ID, USAGE_ID, AMOUNT_OF_MONEY) VALUES (1, '2022-11-10', 0, 1, 1, 1000);
INSERT INTO IncomeAndExpenditure(USER_ID, DATE, IN_OUT, MONEY_SOURCE_ID, USAGE_ID, AMOUNT_OF_MONEY) VALUES (2, '2022-11-10', 0, 2, 2, 1000);
INSERT INTO IncomeAndExpenditure(USER_ID, DATE, IN_OUT, MONEY_SOURCE_ID, USAGE_ID, AMOUNT_OF_MONEY) VALUES (1, '2022-11-10', 1, 1, 3, 1000);
INSERT INTO IncomeAndExpenditure(USER_ID, DATE, IN_OUT, MONEY_SOURCE_ID, USAGE_ID, AMOUNT_OF_MONEY) VALUES (2, '2022-11-10', 1, 2, 4, 1000);
INSERT INTO IncomeAndExpenditure(USER_ID, DATE, IN_OUT, MONEY_SOURCE_ID, USAGE_ID, AMOUNT_OF_MONEY) VALUES (1, '2022-11-10', 0, 1, 1, 1000);
INSERT INTO IncomeAndExpenditure(USER_ID, DATE, IN_OUT, MONEY_SOURCE_ID, USAGE_ID, AMOUNT_OF_MONEY) VALUES (2, '2022-11-10', 0, 2, 2, 1000);
INSERT INTO IncomeAndExpenditure(USER_ID, DATE, IN_OUT, MONEY_SOURCE_ID, USAGE_ID, AMOUNT_OF_MONEY) VALUES (1, '2022-11-10', 1, 1, 3, 1000);
INSERT INTO IncomeAndExpenditure(USER_ID, DATE, IN_OUT, MONEY_SOURCE_ID, USAGE_ID, AMOUNT_OF_MONEY) VALUES (2, '2022-11-10', 1, 2, 4, 1000);
INSERT INTO IncomeAndExpenditure(USER_ID, DATE, IN_OUT, MONEY_SOURCE_ID, USAGE_ID, AMOUNT_OF_MONEY) VALUES (1, '2022-11-11', 0, 1, 1, 1000);
INSERT INTO IncomeAndExpenditure(USER_ID, DATE, IN_OUT, MONEY_SOURCE_ID, USAGE_ID, AMOUNT_OF_MONEY) VALUES (2, '2022-11-11', 0, 2, 2, 1000);
INSERT INTO IncomeAndExpenditure(USER_ID, DATE, IN_OUT, MONEY_SOURCE_ID, USAGE_ID, AMOUNT_OF_MONEY) VALUES (1, '2022-11-11', 1, 1, 3, 1000);
INSERT INTO IncomeAndExpenditure(USER_ID, DATE, IN_OUT, MONEY_SOURCE_ID, USAGE_ID, AMOUNT_OF_MONEY) VALUES (2, '2022-11-11', 1, 2, 4, 1000);


INSERT INTO MoneySources(USER_ID, MONEY_SOURCE_NAME) VALUES (1, 'お財布1');
INSERT INTO MoneySources(USER_ID, MONEY_SOURCE_NAME) VALUES (2, 'お財布1');
INSERT INTO MoneySources(USER_ID, MONEY_SOURCE_NAME) VALUES (1, 'お財布2');
INSERT INTO MoneySources(USER_ID, MONEY_SOURCE_NAME) VALUES (2, 'お財布2');


INSERT INTO Usages(USER_ID, USAGE_NAME, IN_OUT) VALUES (1, '臨時収入', 0);
INSERT INTO Usages(USER_ID, USAGE_NAME, IN_OUT) VALUES (2, '臨時収入', 0);
INSERT INTO Usages(USER_ID, USAGE_NAME, IN_OUT) VALUES (1, '趣味', 1);
INSERT INTO Usages(USER_ID, USAGE_NAME, IN_OUT) VALUES (2, '趣味', 1);